/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmtransaction;

import javax.swing.JOptionPane;

/**
 *
 * @author Yusata
 */
public class PreferenceWith extends javax.swing.JFrame{
String amountwith;
    public int balance=50000;

    /**
     * Creates new form PreferenceWith
     */
    public PreferenceWith() {
        initComponents();
       
        jLabel3.setText("Your account Balance is  :  "+balance);
    }
    public PreferenceWith(int pass)
    {
        initComponents();
        balance=pass;
        jLabel3.setText("Your account Balance is  :  "+balance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atm Transaction System");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("icon.png")).getImage ());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setText("Preference");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));

        jRadioButton2.setText("Default Setting");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, -1, -1));

        jRadioButton3.setText("2000Rs ");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jRadioButton4.setText("500Rs");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, -1, -1));

        jRadioButton5.setText("100Rs");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 102));
        jLabel2.setText("Select Your Preference");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, -1, -1));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmtransaction/home.jpg"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmtransaction/preference1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected())
        {
            jRadioButton2.setVisible(false);
            
            
        }
        else{
           jRadioButton2.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton3.isSelected())
            {
                jRadioButton4.setVisible(false);
                jRadioButton5.setVisible(false);
            }
        else
        {
            jRadioButton4.setVisible(true);
                jRadioButton5.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton4.isSelected())
            {
                jRadioButton3.setVisible(false);
                jRadioButton5.setVisible(false);
            }
        else
        {
            jRadioButton3.setVisible(true);
                jRadioButton5.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton5.isSelected())
            {
                jRadioButton4.setVisible(false);
                jRadioButton3.setVisible(false);
            }
        else
        {
            jRadioButton4.setVisible(true);
                jRadioButton3.setVisible(true);
        }
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int rem;
        amountwith= JOptionPane.showInputDialog("Enter amount to be withdrawal");
        if(Integer.parseInt(amountwith)<=balance)
        {
        if(jRadioButton3.isSelected())
        {
            int a=Integer.parseInt(amountwith)/2000;
            rem=Integer.parseInt(amountwith)-a*2000;
            int b=rem/500;
             rem=rem-b*500;
            int c=rem/100;
            JOptionPane.showMessageDialog(this,"You get 2000 note is"+a);
            JOptionPane.showMessageDialog(this,"You get 500 note is"+b);
            JOptionPane.showMessageDialog(this,"You get 100 note is"+c);
            int e=Integer.parseInt(amountwith);
            balance=balance-e;
            jLabel3.setText("Your account Balance is  :  "+balance);
        }
         if(jRadioButton4.isSelected())
        {
            int a=Integer.parseInt(amountwith)/500;
            rem=Integer.parseInt(amountwith)-a*500;
            int b=rem/100;
             rem=rem-b*100;
            int c=rem/2000;
            JOptionPane.showMessageDialog(this,"You get 500 note is"+a);
            JOptionPane.showMessageDialog(this,"You get 100 note is"+b);
            JOptionPane.showMessageDialog(this,"You get 2000 note is"+c);
             int e=Integer.parseInt(amountwith);
            balance=balance-e;
            jLabel3.setText("Your account Balance is  :  "+balance);
        }
           if(jRadioButton5.isSelected())
        {
            int a=Integer.parseInt(amountwith)/100;
            rem=Integer.parseInt(amountwith)-a*100;
            int b=rem/500;
             rem=rem-b*500;
            int c=rem/2000;
            JOptionPane.showMessageDialog(this,"You get 100 note is"+a);
            JOptionPane.showMessageDialog(this,"You get 500 note is"+b);
            JOptionPane.showMessageDialog(this,"You get 2000 note is"+c);
             int e=Integer.parseInt(amountwith);
            balance=balance-e;
            jLabel3.setText("Your account Balance is  :  "+balance);
        }
          if(jRadioButton2.isSelected())
        {
            int a=Integer.parseInt(amountwith)/2000;
            rem=Integer.parseInt(amountwith)-a*2000;
            int b=rem/500;
             rem=rem-b*500;
            int c=rem/100;
            JOptionPane.showMessageDialog(this,"You get 2000 note is"+a);
            JOptionPane.showMessageDialog(this,"You get 500 note is"+b);
            JOptionPane.showMessageDialog(this,"You get 100 note is"+c);
             int e=Integer.parseInt(amountwith);
            balance=balance-e;
            jLabel3.setText("Your account Balance is  :  "+balance);
        } 
        }
        else
        {
             JOptionPane.showMessageDialog(this,"You enter more then your account balance");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dispose();
        new MainPanel().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PreferenceWith.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PreferenceWith.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PreferenceWith.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreferenceWith.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PreferenceWith().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    // End of variables declaration//GEN-END:variables
}
